name: 'ci'

on: [push]

jobs:
  terraform:
    name: terrform-aws-label
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Lint module
      uses: actionshub/terraform-lint@master
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Run Go Tests
      working-directory: test
      run: go test
